// <auto-generated />
namespace Services.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PriorityAndTask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriorityAndTask));
        
        string IMigrationMetadata.Id
        {
            get { return "202112092144072_PriorityAndTask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
